#!/bin/bash
#
# Recorre todos los archivos del directorio actual y los muestra
for i in $(ls -C1)
do
      cat /home/dpuerto/Documents/Masivo/Base/$i | tr -d "\n\t\r" >> REsultado
      echo "\n" >> REsultado
      echo $i
done